apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: k8s-resources-task
spec:
  description: >-
    These tasks will proform k8s-resources commands
  params:
    - name: REPO_URL_K8S_RESOURCES
      type: string
      description: Repository URL to clone from. (required)
    - name: BASE_IMAGE
      description: "Base image that has Helm, Kubectl, gomplate & skaffold installed."
      default: "mbwali/k8s-resources:latest"
    - name: COMMAND
      type: string
      description: Command to run. (required)
      default: kubectl get nodes
    - name: ENV
      type: string
      description: ENV to run on. (required)
      default: qa
    - name: PROJECTS
      type: array
      description: List of projects
      default: []
    - name: userHome
      description: |
        Absolute path to the user's home directory.
      type: string
      default: "/home/k8s"
  workspaces:
  - name: k8sdata
    description: Holds the cloned repository.
  steps:

    - name: clone
      workingDir: $(workspaces.k8sdata.path)
      # image: mbwali/bash-git:rootless
      image: $(params.BASE_IMAGE)
      imagePullPolicy: Always
      # securityContext:
      #   runAsUser: 0
      env:
      - name: PRV_KEY              
        valueFrom:
          secretKeyRef:
            name: ssh-key
            key: id_rsa
      - name: KNOWN_HOST             
        valueFrom:
          secretKeyRef:
            name: ssh-key
            key: known_hosts
      - name: PARAM_USER_HOME
        value: $(params.userHome)

      script: |
        echo -e "\033[1;33m Cloning $(params.REPO_URL_K8S_RESOURCES) ...  \e[0m"
        whoami
        ls
        echo "read the private key---- $PRV_KEY"
        echo "read the known_hosts---- $KNOWN_HOST"

        echo "$PRV_KEY" > "$PARAM_USER_HOME/.ssh/id_rsa"
        echo "$KNOWN_HOST" > "$PARAM_USER_HOME/.ssh/known_hosts"
        chmod -R 700 "$PARAM_USER_HOME/.ssh/id_rsa"
        ls

        git clone --progress $(params.REPO_URL_K8S_RESOURCES) --single-branch .
        echo -e "\033[1;33m Successfully cloned to . \e[0m"

        rm -r $PARAM_USER_HOME/.ssh/
        
        pwd

        git config --global --add safe.directory /workspace/k8sdata

        ls
        echo -e "\033[1;33m Successfully cloned to . \e[0m"

  
    - name: generate-load
      workingDir: $(workspaces.k8sdata.path)
      image: $(params.BASE_IMAGE)
      imagePullPolicy: Always
      # securityContext:
      #   runAsUser: 0
      script: |
        #!/bin/bash
        ls 
        echo -e "\033[1;33m Check versions...  \e[0m"
        whoami
        gomplate --version
        go version
        kubectl version -o json
        echo -e "\033[1;33m ENV is $(params.ENV)...  \e[0m"
        echo -e "\033[1;33m Generating config/secrets \e[0m"
        ./generate_configs.py -e $(params.ENV)
        ./generate_secrets.py -e $(params.ENV)
        echo -e "\033[1;33m Done Generating... \e[0m"
        echo -e "\033[1;33m Loading config/secrets \e[0m"
        ./load_configs.py -e $(params.ENV) -n $(params.ENV) 
        ./load_secrets.py -e $(params.ENV) -n $(params.ENV)
        echo -e "\033[1;33m Done Loading config/secrets... \e[0m"

    - name: k8s-resources
      workingDir: $(workspaces.k8sdata.path)
      image: $(params.BASE_IMAGE)
      imagePullPolicy: Always
      # securityContext:
      #   runAsUser: 0
      args:
        - "$(params.PROJECTS[*])"
      script: |
        #!/bin/bash
        echo -e "\033[1;33m Deploying Step... \e[0m"
        projects=()
        for arg in "$@"; do
          echo "$arg"
          projects+=("$arg")
        done
        for project in "${projects[@]}"; do
          echo -e "\033[1;33m Deploying $project into the namespace $(params.ENV)... \e[0m"
          ./deploy.py -Bn $(params.ENV) -p $project -C
        done
 

