apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: k8s-resources-pipeline
spec:
  description: |
    This pipeline clones a git repo, package a helm chart and
    pushes it to a registry
  workspaces:
  - name: ssh-creds
  - name: shared-data
  - name: shared-data2

  params:
  # git-clone param
  - name: docker-data-repo-url
    type: string
    description: Repository URL to clone from. (required)
  - name: k8s-resources-repo-url
    type: string
    description: Repository URL to clone from. (required)
  
  # kubectl param
  - name: ENV
    type: string
    description: Env to run on - (required)
  - name: COMMAND
    type: string
    description: Kubectl command - (required)
  - name: BASE_IMAGE
    type: string
    description: Base Image to run - (required)
  - name: PROJECTS
    type: array
    description: List of projects

  tasks:
  - name: clone-docker-data-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: ssh-directory # ssh keys via secret
      workspace: ssh-creds
    - name: output  # clone repo location
      workspace: shared-data
    params:
    - name: url
      value: $(params.docker-data-repo-url)

  # task: command
  - name: docker-data
    runAfter: ["clone-docker-data-repo"]
    taskRef:
      name: docker-data-task
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: ENV
      value: $(params.ENV)
    - name: BASE_IMAGE
      value: $(params.BASE_IMAGE)


####################################################################
  # Task cloning private repo
  - name: clone-k8s-resources-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: ssh-directory # ssh keys via secret
      workspace: ssh-creds
    - name: output2  # clone repo location
      workspace: shared-data2
    params:
    - name: url
      value: $(params.k8s-resources-repo-url)

  # task: command
  - name: k8s-resources
    runAfter: ["clone-k8s-resources-repo"]
    taskRef:
      name: k8s-resources-task
    workspaces:
    - name: source2
      workspace: shared-data2
    params:
    - name: ENV
      value: $(params.ENV)
    - name: COMMAND
      value: $(params.COMMAND)
    - name: BASE_IMAGE
      value: $(params.BASE_IMAGE)
    - name: PROJECTS
      value: ["$(params.PROJECTS[*])"]
