apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: k8s-resources-pipeline
spec:
  description: |
    This pipeline clones a git repo, package a helm chart and
    pushes it to a registry
  workspaces:
  - name: ssh-creds

  params:
  
  # kubectl param
  - name: ENV
    type: string
    description: Env to run on - (required)
  - name: BASE_IMAGE
    type: string
    description: Base Image to run - (required)
  - name: PROJECTS
    type: array
    description: List of projects
  - name: REPO_URL_K8S_RESOURCES
    type: string
    description: Repository URL to clone from. (required)
  - name: K8S_RESOURCES_BRANCH
    type: string
    description: Repository branch to clone. (_default_ main)
  
  # docker data param
  - name: REPO_URL_DOCKER_DATA
    type: string
    description: Repository URL to clone from. (required)

  tasks:
  # task: command
  - name: docker-data
    taskRef:
      name: docker-data-task
    params:
    - name: ENV
      value: $(params.ENV)
    - name: BASE_IMAGE
      value: $(params.BASE_IMAGE)
    - name: REPO_URL_DOCKER_DATA
      value: $(params.REPO_URL_DOCKER_DATA)

  # task: k8s-resources
  - name: k8s-resources
    taskRef:
      name: k8s-resources-task
    params:
    - name: ENV
      value: $(params.ENV)
    - name: BASE_IMAGE
      value: $(params.BASE_IMAGE)
    - name: PROJECTS
      value: ["$(params.PROJECTS[*])"]
    - name: REPO_URL_K8S_RESOURCES
      value: $(params.REPO_URL_K8S_RESOURCES)
    - name: K8S_RESOURCES_BRANCH
      value: $(params.K8S_RESOURCES_BRANCH)
