apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-kubectl
spec:
  description: >-
    These tasks will proform k8s-resources commands
  params:
    - name: HELM_IMAGE
      description: "Helm image that has Helm, Kubectl and gomplate installed."
      default: "mbwali/k8s-resources:latest"
    # - name: REPO_URL
    #   type: string
    #   description: Repository URL to clone from. (required)
    - name: COMMAND
      type: string
      description: Command to run. (required)
      default: kubectl get nodes
    - name: ENV
      type: string
      description: ENV to run on. (required)
      default: qa
  workspaces:
  - name: source
    description: Holds the cloned helm chart repository.
  steps:
    - name: generate_load
      workingDir: $(workspaces.source.path)
      image: $(params.HELM_IMAGE)
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
      script: |
        whoami
        ls
        gomplate --help
        kubectl version
        echo -e "\033[1;33m ENV is $(params.ENV)...  \e[0m"
        echo "This was the first command.."
        ls resources/configs
        ./generate_configs.py -e $(params.ENV)
        ./generate_secrets.py -e $(params.ENV)
        ./load_configs.py -e $(params.ENV) -n $(params.ENV) 
        ./load_secrets.py -e $(params.ENV) -n $(params.ENV) 
        
    - name: command
      workingDir: $(workspaces.source.path)
      image: $(params.HELM_IMAGE)
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
      script: |
        echo -e "\033[1;33m Start command $(params.COMMAND)...  \e[0m"
        ls
        $(params.COMMAND)
        