apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: k8s-resources-task
spec:
  description: >-
    These tasks will proform k8s-resources commands
  params:
    - name: BASE_IMAGE
      description: "Base image that has Helm, Kubectl, gomplate & skaffold installed."
      default: "mbwali/k8s-resources:latest"
    # - name: REPO_URL
    #   type: string
    #   description: Repository URL to clone from. (required)
    - name: COMMAND
      type: string
      description: Command to run. (required)
      default: kubectl get nodes
    - name: ENV
      type: string
      description: ENV to run on. (required)
      default: qa
    - name: PROJECTS
      type: array
      description: List of projects
  workspaces:
  - name: source
    description: Holds the cloned helm chart repository.
  steps:
    - name: generate-load
      workingDir: $(workspaces.source.path)
      image: $(params.BASE_IMAGE)
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
      script: |
        echo -e "\033[1;33m Check versions...  \e[0m"
        whoami
        ls
        gomplate --help
        kubectl version
        echo -e "\033[1;33m ENV is $(params.ENV)...  \e[0m"
        echo -e "\033[1;33m generate and load config/secrets \e[0m"
        ./generate_configs.py -e $(params.ENV)
        ./generate_secrets.py -e $(params.ENV)
        ./load_configs.py -e $(params.ENV) -n $(params.ENV) 
        ./load_secrets.py -e $(params.ENV) -n $(params.ENV) 
        
    - name: command
      workingDir: $(workspaces.source.path)
      image: $(params.BASE_IMAGE)
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
      script: |
        echo -e "\033[1;33m Run the given command... \e[0m"
        $(params.COMMAND)
        